name: delivery_sidekick
description: Companion app for service delivery drivers to track their tips and mileage

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Authentication
  google_sign_in: ^3.2.4
  firebase_auth: ^0.6.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
