name: delivery_sidekick
description: Companion app for service delivery drivers to track their tips and mileage

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Authentication
  validate: ^1.7.0
  google_sign_in: ^3.2.2
  firebase_auth: ^0.6.2+1

  # Database
  cloud_firestore: ^0.8.2+3

  # Tracking
  money: ^0.2.1
  geolocator: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/email.png
    - assets/images/google.png
